
version: '3'

services:
  hr-portal-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST:-localhost}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin}
      - DB_NAME=${DB_NAME:-hr_portal}
      - DB_PORT=${DB_PORT:-3306}
    restart: unless-stopped
