
name: HR Portal AWS Deployment
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy
      confirmation:
        description: 'Type "destroy" to confirm deletion of all resources'
        required: false
        type: string

jobs:
  check:
    uses: ./.github/workflows/check_resources.yml
    secrets: inherit
  
  deploy:
    needs: check
    if: ${{ github.event.inputs.action != 'destroy' }}
    uses: ./.github/workflows/deploy_resources.yml
    with:
      action: ${{ github.event.inputs.action }}
    secrets: inherit
  
  destroy:
    needs: check
    if: ${{ github.event.inputs.action == 'destroy' }}
    uses: ./.github/workflows/destroy_resources.yml
    with:
      confirmation: ${{ github.event.inputs.confirmation }}
    secrets: inherit
  
  display_urls:
    needs: [check, deploy]
    if: ${{ always() && github.event.inputs.action != 'destroy' }}
    uses: ./.github/workflows/display_urls.yml
    with:
      existing_resources: ${{ needs.check.outputs.existing_resources }}
      terraform_deployed: ${{ needs.check.outputs.terraform_deployed }}
      check_ec2_ip: ${{ needs.check.outputs.ec2_ip }}
      check_alb_dns: ${{ needs.check.outputs.alb_dns }}
      check_api_url: ${{ needs.check.outputs.api_url }}
      deploy_ec2_ip: ${{ needs.deploy.outputs.ec2_ip }}
      deploy_alb_dns: ${{ needs.deploy.outputs.alb_dns }}
      deploy_api_url: ${{ needs.deploy.outputs.api_url }}
    secrets: inherit
