
name: HR Portal - Deploy Application
on:
  workflow_call:
    inputs:
      instance_id:
        description: 'EC2 instance ID'
        type: string
        required: true
      ec2_ip:
        description: 'EC2 IP address'
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  s3_operations:
    runs-on: ubuntu-latest
    if: ${{ inputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/s3_operations.yml
    with:
      instance_id: ${{ inputs.instance_id }}
    secrets: inherit
    
  docker_setup:
    runs-on: ubuntu-latest
    needs: s3_operations
    if: ${{ inputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/docker_operations.yml
    with:
      instance_id: ${{ inputs.instance_id }}
      bucket_name: ${{ needs.s3_operations.outputs.bucket_name }}
    secrets: inherit
    
  deploy_container:
    runs-on: ubuntu-latest
    needs: [s3_operations, docker_setup]
    if: ${{ inputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/deploy_container.yml
    with:
      instance_id: ${{ inputs.instance_id }}
      bucket_name: ${{ needs.s3_operations.outputs.bucket_name }}
    secrets: inherit
    
  verify_deployment:
    runs-on: ubuntu-latest
    needs: deploy_container
    if: ${{ inputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/verify_deployment.yml
    with:
      instance_id: ${{ inputs.instance_id }}
      ec2_ip: ${{ inputs.ec2_ip }}
    secrets: inherit
    
  preserve_bucket_info:
    runs-on: ubuntu-latest
    needs: [s3_operations, verify_deployment]
    if: ${{ always() && inputs.instance_id != 'unavailable' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Leave S3 bucket intact
        run: |
          BUCKET_NAME="${{ needs.s3_operations.outputs.bucket_name }}"
          
          if [ -n "$BUCKET_NAME" ]; then
            echo "Keeping S3 bucket: $BUCKET_NAME intact for future use"
            echo "Bucket URL: s3://$BUCKET_NAME"
            
            # List the contents of the bucket
            echo "Contents of the bucket:"
            aws s3 ls "s3://$BUCKET_NAME/"
            
            # Create a public URL for the object
            echo "S3 URL: https://$BUCKET_NAME.s3.amazonaws.com/hr-portal-app.tar"
          else
            echo "Bucket name not available"
          fi
