
name: HR Portal - Deploy Resources
on:
  workflow_call:
    inputs:
      action:
        description: 'Action to perform'
        type: string
        required: true
        default: 'deploy'
    outputs:
      ec2_ip:
        description: "EC2 instance public IP"
        value: ${{ jobs.deploy_infrastructure.outputs.ec2_ip }}
      api_url:
        description: "API Gateway URL"
        value: ${{ jobs.deploy_infrastructure.outputs.api_url }}
      alb_dns:
        description: "ALB DNS name"
        value: ${{ jobs.deploy_infrastructure.outputs.alb_dns }}
      instance_id:
        description: "EC2 instance ID"
        value: ${{ jobs.deploy_infrastructure.outputs.instance_id }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy_infrastructure:
    if: ${{ inputs.action != 'destroy' }}
    uses: ./.github/workflows/deploy_infrastructure.yml
    with:
      action: ${{ inputs.action }}
    secrets: inherit
  
  wait_for_instance:
    needs: deploy_infrastructure
    if: ${{ inputs.action != 'destroy' && needs.deploy_infrastructure.outputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/wait_for_instance.yml
    with:
      instance_id: ${{ needs.deploy_infrastructure.outputs.instance_id }}
    secrets: inherit
  
  verify_ssm:
    needs: [deploy_infrastructure, wait_for_instance]
    if: ${{ inputs.action != 'destroy' && needs.deploy_infrastructure.outputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/verify_ssm_agent.yml
    with:
      instance_id: ${{ needs.deploy_infrastructure.outputs.instance_id }}
    secrets: inherit

  verify_docker:
    needs: [deploy_infrastructure, wait_for_instance, verify_ssm]
    if: ${{ inputs.action != 'destroy' && needs.deploy_infrastructure.outputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/verify_docker.yml
    with:
      instance_id: ${{ needs.deploy_infrastructure.outputs.instance_id }}
    secrets: inherit
  
  deploy_application:
    needs: [deploy_infrastructure, wait_for_instance, verify_ssm, verify_docker]
    if: ${{ inputs.action != 'destroy' && needs.deploy_infrastructure.outputs.instance_id != 'unavailable' }}
    uses: ./.github/workflows/deploy_application.yml
    with:
      instance_id: ${{ needs.deploy_infrastructure.outputs.instance_id }}
      ec2_ip: ${{ needs.deploy_infrastructure.outputs.ec2_ip }}
    secrets: inherit

  display_deployment_info:
    needs: [deploy_infrastructure, deploy_application]
    if: ${{ inputs.action != 'destroy' && always() }}
    uses: ./.github/workflows/display_urls.yml
    with:
      ec2_ip: ${{ needs.deploy_infrastructure.outputs.ec2_ip }}
      alb_dns: ${{ needs.deploy_infrastructure.outputs.alb_dns }}
      api_url: ${{ needs.deploy_infrastructure.outputs.api_url }}
    secrets: inherit
