
name: Destroy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm deletion of all resources'
        required: true
        type: string

jobs:
  check_resources:
    uses: ./.github/workflows/check-resources.yml
  
  destroy:
    needs: check_resources
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'destroy' && needs.check_resources.outputs.existing_resources == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      
      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve -var="db_username=admin" -var="db_password=password123"
          
      - name: Confirmation
        run: |
          echo "All AWS resources have been successfully destroyed."
