
name: HR Portal - Destroy Resources
on:
  workflow_call:
    inputs:
      confirmation:
        description: 'Confirmation string to destroy resources'
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  destroy:
    if: ${{ inputs.confirmation == 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      
      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve -var="db_username=admin" -var="db_password=password123"
          
      - name: Confirmation
        run: |
          echo "All AWS resources have been successfully destroyed."
