
name: HR Portal - Display URLs
on:
  workflow_call:
    inputs:
      ec2_ip:
        description: 'EC2 IP address'
        type: string
        required: true
        default: 'unavailable'
      alb_dns:
        description: 'ALB DNS name'
        type: string
        required: true
        default: 'unavailable'
      api_url:
        description: 'API Gateway URL'
        type: string
        required: true
        default: 'unavailable'

jobs:
  display_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Display deployment URLs
        run: |
          echo "============= DEPLOYMENT INFORMATION ============="
          echo "HR Portal has been deployed successfully!"
          echo ""
          
          if [ "${{ inputs.alb_dns }}" != "unavailable" ]; then
            echo "Application Load Balancer (ALB) URL:"
            echo "http://${{ inputs.alb_dns }}"
          else
            echo "ALB URL: Not available"
          fi
          
          echo ""
          
          if [ "${{ inputs.api_url }}" != "unavailable" ]; then
            echo "API Gateway URL:"
            echo "${{ inputs.api_url }}"
          else
            echo "API Gateway URL: Not available"
          fi
          
          echo ""
          
          if [ "${{ inputs.ec2_ip }}" != "unavailable" ]; then
            echo "EC2 Instance Direct URL (for debugging):"
            echo "http://${{ inputs.ec2_ip }}"
          else
            echo "EC2 Direct URL: Not available"
          fi
          
          echo "=================================================="
