
name: HR Portal - Docker Operations
on:
  workflow_call:
    inputs:
      instance_id:
        description: 'EC2 instance ID'
        type: string
        required: true
      bucket_name:
        description: 'S3 bucket name'
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  docker_operations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Verify Docker Installation on EC2
        if: ${{ inputs.instance_id != 'unavailable' }}
        run: |
          INSTANCE_ID=${{ inputs.instance_id }}
          
          echo "Running thorough Docker installation verification..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=$INSTANCE_ID" \
            --parameters '{"commands":[
              "echo \"===== CHECKING DOCKER INSTALLATION =====\" > /tmp/docker-verification.log",
              "echo \"Command check:\" >> /tmp/docker-verification.log",
              "command -v docker >> /tmp/docker-verification.log 2>&1 || echo \"Docker command not found\" >> /tmp/docker-verification.log",
              "echo \"Package check:\" >> /tmp/docker-verification.log",
              "yum list installed docker >> /tmp/docker-verification.log 2>&1 || echo \"Docker package not found\" >> /tmp/docker-verification.log",
              "echo \"Version check:\" >> /tmp/docker-verification.log",
              "docker --version >> /tmp/docker-verification.log 2>&1 || echo \"Docker version command failed\" >> /tmp/docker-verification.log",
              "echo \"Service check:\" >> /tmp/docker-verification.log",
              "systemctl status docker >> /tmp/docker-verification.log 2>&1 || echo \"Docker service not running\" >> /tmp/docker-verification.log",
              "echo \"===== INSTALLING/REINSTALLING DOCKER IF NEEDED =====\" >> /tmp/docker-verification.log",
              "amazon-linux-extras install -y docker >> /tmp/docker-verification.log 2>&1 || yum install -y docker >> /tmp/docker-verification.log 2>&1",
              "systemctl enable docker >> /tmp/docker-verification.log 2>&1",
              "systemctl restart docker >> /tmp/docker-verification.log 2>&1",
              "echo \"===== FINAL VERIFICATION =====\" >> /tmp/docker-verification.log",
              "docker --version >> /tmp/docker-verification.log 2>&1",
              "systemctl status docker >> /tmp/docker-verification.log 2>&1",
              "echo \"===== VERIFICATION COMPLETE =====\" >> /tmp/docker-verification.log",
              "cat /tmp/docker-verification.log"
            ]}' \
            --comment "Thorough Docker verification"
          
          # Wait for the verification to complete
          echo "Waiting for Docker verification to complete..."
          sleep 30
      
      - name: Create and prepare hrApp directory
        if: ${{ inputs.instance_id != 'unavailable' }}
        run: |
          INSTANCE_ID=${{ inputs.instance_id }}
          
          echo "Creating and preparing /tmp/hrApp directory with proper permissions..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=$INSTANCE_ID" \
            --parameters '{"commands":[
              "echo \"===== PREPARING DIRECTORY =====\" > /tmp/dir-preparation.log",
              "mkdir -p /tmp/hrApp",
              "chmod -R 777 /tmp/hrApp",
              "echo \"Directory created at $(date)\" >> /tmp/dir-preparation.log",
              "echo \"Directory permissions:\" >> /tmp/dir-preparation.log",
              "ls -la /tmp | grep hrApp >> /tmp/dir-preparation.log",
              "echo \"Current user: $(whoami)\" >> /tmp/dir-preparation.log",
              "echo \"AWS CLI version:\" >> /tmp/dir-preparation.log",
              "aws --version >> /tmp/dir-preparation.log 2>&1 || echo \"AWS CLI not installed\" >> /tmp/dir-preparation.log",
              "if ! command -v aws &> /dev/null; then",
              "  echo \"Installing AWS CLI...\" >> /tmp/dir-preparation.log",
              "  yum install -y aws-cli >> /tmp/dir-preparation.log 2>&1",
              "fi",
              "echo \"===== DIRECTORY PREPARATION COMPLETE =====\" >> /tmp/dir-preparation.log",
              "cat /tmp/dir-preparation.log"
            ]}' \
            --comment "Prepare hrApp directory"
          
          echo "Waiting for directory preparation to complete..."
          sleep 20
