
name: HR Portal - Verify Docker
on:
  workflow_call:
    inputs:
      instance_id:
        description: 'EC2 instance ID'
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  verify_docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Test Docker installation and prepare environment
        if: ${{ inputs.instance_id != 'unavailable' }}
        run: |
          INSTANCE_ID=${{ inputs.instance_id }}
          
          if [ "$INSTANCE_ID" == "unavailable" ]; then
            echo "Instance ID not available. Skipping Docker verification."
            exit 0
          fi
          
          echo "Verifying Docker installation on instance $INSTANCE_ID..."
          
          # Use SSM to check Docker installation
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=$INSTANCE_ID" \
            --parameters 'commands=[
              "echo \"===== DOCKER VERIFICATION =====\"",
              "# Check if Docker is installed",
              "if ! command -v docker &> /dev/null; then",
              "  echo \"Docker is not installed. Installing...\"",
              "  amazon-linux-extras install -y docker || yum install -y docker",
              "  systemctl enable docker",
              "  systemctl start docker",
              "  echo \"Docker installation complete.\"",
              "else",
              "  echo \"Docker is already installed.\"",
              "fi",
              
              "# Check if Docker service is running",
              "if ! systemctl is-active --quiet docker; then",
              "  echo \"Docker service is not running. Starting...\"",
              "  systemctl start docker",
              "  echo \"Docker service started.\"",
              "else",
              "  echo \"Docker service is running.\"",
              "fi",
              
              "# Verify Docker is working",
              "echo \"Testing Docker with hello-world container...\"",
              "docker run --rm hello-world | grep \"Hello from Docker!\" && echo \"Docker is working correctly.\" || echo \"Docker test failed.\"",
              
              "# Create application directory",
              "echo \"Creating application directory...\"",
              "mkdir -p /tmp/hrApp",
              "chmod -R 777 /tmp/hrApp",
              "echo \"Directory prepared at $(date)\" > /tmp/hrApp/prepared.txt",
              "echo \"===== VERIFICATION COMPLETE =====\""
            ]' \
            --comment "Verify Docker installation"
          
          # Allow time for command to complete
          echo "Waiting for Docker verification to complete (30 seconds)..."
          sleep 30
