
name: HR Portal - Verify Deployment
on:
  workflow_call:
    inputs:
      instance_id:
        description: 'EC2 instance ID'
        type: string
        required: true
      ec2_ip:
        description: 'EC2 IP address'
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  verify_deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Verify Deployment
        if: ${{ inputs.instance_id != 'unavailable' }}
        run: |
          INSTANCE_ID=${{ inputs.instance_id }}
          EC2_IP=${{ inputs.ec2_ip }}
          
          echo "Waiting 30 seconds for container to fully initialize..."
          sleep 30
          
          echo "Verifying deployment..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=$INSTANCE_ID" \
            --parameters '{"commands":[
              "echo \"===== DEPLOYMENT VERIFICATION =====\"",
              "echo \"Container status:\"",
              "sudo docker ps",
              "echo \"Container logs:\"",
              "sudo docker logs hr-portal-container 2>&1 || echo \"No logs available\"",
              "echo \"Web server response:\"",
              "curl -s -o /dev/null -w \"%{http_code}\" http://localhost || echo \"Failed to connect\"",
              "echo \"Files in /tmp/hrApp:\"",
              "ls -la /tmp/hrApp/",
              "echo \"Docker images:\"",
              "sudo docker images",
              "echo \"System disk space:\"",
              "df -h",
              "echo \"===== VERIFICATION COMPLETE =====\""
            ]}' \
            --comment "Verify HR Portal container deployment"
